[build]
builder = "nixpacks"

[deploy]
startCommand = "celery -A app.workers.tasks beat --loglevel=info"
restartPolicyType = "on_failure"

[environments.production]
  [environments.production.deploy]
    numReplicas = 1
